version: "3.9"

services:

  eureka-server:
    image: openjdk:21

  api-gateway:
    image: openjdk:21

  customer-service:
    image: openjdk:21

  product-service:
    image: openjdk:21

  order-service:
    image: openjdk:21
