spring.application.name=enterprise-digital-transformation-platform

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/digital_transformation_db
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*
