spring.application.name=workflow-automation-platform

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/workflow_db
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin123
